title: ewen
description: Ewen's home page on the World Wide Web.
url: https://ewen.io
permalink: /posts/:title
timezone: Europe/London
kramdown:
  hard_wrap: true
sass:
  sass_dir: assets
  style: compressed
collections:
  sounds:
    output: true
  notes:
    output: true
  pages:
    output: true
  playing:
    output: true
  reading:
    output: true
  watching:
    output: true
pagination:
  enabled: true
  per_page: 20
  sort_field: "date"
  sort_reverse: true
plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2
defaults:
  -
    scope:
      path: "_reading" # an empty string here means all files in the project
    values:
      layout: "reading"
      permalink: /log/:name/
  -
    scope:
      path: "_playing"
    values:
      layout: "playing"
      permalink: /log/:name/
  -
    scope:
      path: "_watching"
    values:
      layout: "watching"
      permalink: /log/:name/
